export type Link = {
  id?: string; // Generated by database
  slug: string;
  url: string;
  userId?: string;
  visitorId: string;
  createdAt?: string; // Generated by database
}

export type LinkGeneration = {
  isGenerated: boolean;
  inGeneration: boolean;

  finalUrl: string;
}