export type Link = {
  id?: string; // Generated by database
  url: string;
  slug: string;
  clicks: number; // Generated by database (Default: 0)
  status?: boolean; // Generated by database (Default: true)
  createdAt?: string; // Generated by database
  userId?: string;
  visitorId: string;
}

export type LinkGeneration = {
  isGenerated: boolean;
  inGeneration: boolean;

  finalUrl: string;
}

export type LinkGenerationOptions = {
  slug: {
    length: number; // Default: 5
    custom: string; // If custom is set, length is ignored
  }
  // password: string;
  // expiration: {
  //   enabled: boolean;
  //   date: string;
  // }
  // subdomain: string;
}